os:
    - linux

language: python

env:
    - TRAVIS_CI=TRAVIS_CI


sudo: true

cache:
    - pip
    - $HOME/virtualenv

python:
    - 2.7
    - 3.4
    - 3.6

install:
    - python setup.py install
    - pip install codecov

script:
    - coverage run -a -m unittest test.client
    - coverage run -a -m unittest test.top
    - coverage run -a -m unittest test.torrent
    - coverage run -a -m unittest test.utils
#    - chmod +x ./ci/install_and_start_downloader
#    - ./ci/install_and_start_downloader
#    - sudo python ./ci/stop_downloader.py

after_success:
  - codecov